# Generated by Django 5.1.3 on 2024-11-29 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='file_updated',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
